### ISSUE TITLE
【建议】开源，将软件发布移至release

### ISSUE THREAD

**Issue by KHLFYY** [CoderLiuChina/SecretMessage_Original#3]
如果此项目开源，请在repo公开源代码。

将repo中的exe移除，exe打包成zip 发布在release

**Comment by CoderLiuChina** [comment]
抱歉
但是这个程序的主要功能是对文章句子进行加密
所以这个程序不会公开源码
但是我会在做完之后放出获取源码的途径
现在只做了一半不到，所以短期内源码不会放出来
